### ISSUE TITLE
Incorrect change of "Unique identifier for the document" in new version of csaf document 

### ISSUE THREAD

**Issue by mfd2007** [secvisogram/csaf-cms-backend#108]
When a new version for an existing csaf document is created, the document gets a new unique identifier. 

Example: `test-2023-00001` will be `test-2023-00002`

This is not correct. If an advisory gets an update, the unique identifier must not be changed.

**Comment by valentindey** [comment]
I am not able to reproduce this and added a check for this here: https://github.com/secvisogram/csaf-cms-backend/pull/109/commits/7b096197bb0daea94a310652af30bb980ce8542e

Can you provide me with the exact steps you took that lead to the incorrect behavior?

**Comment by valentindey** [comment]
Thanks. I thought the incorrect behavior occurred already when creating a new version and did not go through the process of publishing the document again.

Should be fixed in https://github.com/secvisogram/csaf-cms-backend/pull/109 and 1c42cb5e34defb8e13694843533f6a99019fe123 adds an extended test publishing the document several times.
